import { StyleSheet } from "react-native";
import { COLORS, SIZES } from "../../../constants";

export const styles = StyleSheet.create({
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  container: {
    flex: 1,
    backgroundColor: "#f5f5f5",
    marginBottom: 85,
  },
  coverImageContainer: {
    height: 180,
    width: "100%",
    position: "relative",
  },
  coverImage: {
    width: "100%",
    height: "100%",
  },
  imageGradient: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 180,
  },
  communityInfoOverlay: {
    position: "absolute",
    bottom: 15,
    left: 15,
    right: 15,
  },
  communityTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "white",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.5,
    shadowRadius: 2,
  },
  memberCountContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 5,
  },
  memberCountText: {
    color: "white",
    marginLeft: 5,
    fontSize: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.5,
    shadowRadius: 2,
  },
  contentContainer: {
    flex: 1,
  },
  tabContainer: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    backgroundColor: "white",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
  },
  tab: {
    flex: 1,
    paddingVertical: 12,
    alignItems: "center",
  },
  activeTab: {
    borderBottomWidth: 2,
    borderBottomColor: COLORS.primary,
  },
  tabText: {
    fontSize: 16,
    color: "#666",
    fontWeight: "500",
  },
  activeTabText: {
    color: COLORS.primary,
    fontWeight: "bold",
  },
  // Chat styles
  chatContainer: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  messageList: {
    flex: 1,
    padding: SIZES.small,
  },
  messageListContent: {
    paddingBottom: 10,
  },
  messageContainer: {
    flexDirection: "row",
    marginBottom: 10,
    maxWidth: "80%",
  },
  ownMessage: {
    alignSelf: "flex-end",
    justifyContent: "flex-end",
  },
  otherMessage: {
    alignSelf: "flex-start",
  },
  messageAvatar: {
    width: 30,
    height: 30,
    borderRadius: 15,
    marginRight: 8,
  },
  messageBubble: {
    padding: 10,
    borderRadius: 18,
    maxWidth: "100%",
  },
  ownMessageBubble: {
    backgroundColor: COLORS.primary,
    borderBottomRightRadius: 4,
  },
  otherMessageBubble: {
    backgroundColor: "white",
    borderBottomLeftRadius: 4,
  },
  messageAuthor: {
    fontSize: 12,
    alignSelf: "flex-end",
    marginTop: 4,
  },
  messageTime: {
    fontSize: 11,
    color: "#888",
    alignSelf: "flex-end",
    marginTop: 4,
  },
  systemMessageContainer: {
    alignItems: "center",
    marginVertical: 10,
  },
  systemMessageText: {
    fontSize: 12,
    color: "#888",
    alignSelf: "center",
    fontStyle: "italic",
    backgroundColor: "rgba(0,0,0,0.05)",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
  },
  inputContainer: {
    flexDirection: "row",
    padding: 10,
    backgroundColor: "white",
    borderTopWidth: 1,
    borderTopColor: "#eee",
    alignItems: "flex-end",
  },
  messageInput: {
    flex: 1,
    minHeight: 40,
    maxHeight: 100,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 20,
    paddingHorizontal: 15,
    paddingVertical: 8,
    marginRight: 10,
    backgroundColor: "#f9f9f9",
  },
  emptyStateText: {
    textAlign: "center",
    color: "#888",
    padding: 20,
    fontStyle: "italic",
    marginTop: 30,
  },
  deletedBanner: {
    backgroundColor: "#ffebeb",
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#ffcccc",
  },
  deletedText: {
    textAlign: "center",
    color: "#ff3b30",
  },
  messageText: {
    fontSize: 15,
    lineHeight: 20,
    color: "#333",
  },
  headerJoinButton: {
    backgroundColor: "rgba(0,122,255,0.7)",
    paddingVertical: 5,
    paddingHorizontal: 12,
    marginRight: 10,
    borderRadius: 5,
  },
  headerJoinButtonText: {
    textAlign: "center",
    color: "white",
    fontSize: 14,
  },
  memberAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 10,
    borderWidth: 1,
    borderColor: "#eee",
  },
  emptyText: {
    padding: 20,
    textAlign: "center",
    color: "#888",
  },
  // Enhanced About section styles
  aboutContainer: {
    flex: 1,
    backgroundColor: "#f5f5f5",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  statsCard: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  statsRow: {
    flexDirection: "row",
    paddingHorizontal: 16,
    justifyContent: "space-around",
    alignItems: "center",
  },
  statItem: {
    flex: 1,
    alignItems: "center",
  },
  statDivider: {
    height: 40,
    width: 1,
    backgroundColor: "#eee",
  },
  statValue: {
    fontSize: 20,
    fontWeight: "bold",
    color: COLORS.primary,
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: "#777",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  infoCard: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  sectionHeading: {
    fontSize: 18,
    textTransform: "uppercase",
    fontWeight: "600",
    color: "#333",
    marginBottom: 12,
  },
  description: {
    fontSize: 16,
    color: "#444",
    lineHeight: 24,
  },
  membershipCard: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  membershipTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#333",
    marginBottom: 8,
  },
  membershipDescription: {
    fontSize: 14,
    color: "#666",
    marginBottom: 16,
    lineHeight: 20,
  },
  membershipButtonContainer: {
    alignItems: "center",
  },
  joinCommunityButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.primary,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    width: "100%",
  },
  joinCommunityButtonText: {
    color: "white",
    fontWeight: "600",
    fontSize: 16,
  },
  leaveCommunityButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#FF3B30",
    width: "100%",
  },
  leaveCommunityButtonText: {
    color: "#FF3B30",
    fontWeight: "600",
    fontSize: 16,
  },
  buttonIcon: {
    marginRight: 10,
  },
  // Enhanced admin controls
  adminCard: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  adminButtonNew: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: 8,
    marginBottom: 12,
    paddingVertical: 10,
  },
  adminButtonIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  deleteIconContainer: {
    backgroundColor: "#FF3B30",
  },
  adminButtonContent: {
    flex: 1,
  },
  adminButtonTitle: {
    fontSize: 16,
    fontWeight: "500",
    color: "#333",
    marginBottom: 2,
  },
  deleteButtonTitle: {
    fontSize: 16,
    fontWeight: "500",
    color: "#FF3B30",
    marginBottom: 2,
  },
  adminButtonDescription: {
    fontSize: 13,
    color: "#888",
  },
  deleteButtonNew: {
    marginTop: 4,
  },
  // Enhanced chat styles
  chatContainer: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  emptyChatContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 60,
  },
  deletedBanner: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff0f0",
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#ffcccc",
  },
  deletedIcon: {
    marginRight: 8,
  },
  deletedText: {
    flex: 1,
    textAlign: "center",
    color: "#ff3b30",
    fontWeight: "500",
  },
  chatInputWrapper: {
    borderTopWidth: 1,
    borderTopColor: "#eaeaea",
    backgroundColor: "white",
  },
  inputContainer: {
    flexDirection: "row",
    padding: 10,
    alignItems: "flex-end",
  },
  messageInput: {
    flex: 1,
    minHeight: 40,
    maxHeight: 120,
    borderWidth: 1,
    borderColor: "#dedede",
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 10,
    marginRight: 12,
    backgroundColor: "#f9f9f9",
    fontSize: 16,
  },
  sendButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1,
  },
  disabledButton: {
    backgroundColor: "#e0e0e0",
    elevation: 0,
    shadowOpacity: 0,
  },
  joinToChatContainer: {
    padding: 20,
    alignItems: "center",
    backgroundColor: "white",
    borderTopWidth: 1,
    borderTopColor: "#eee",
  },
  lockIcon: {
    marginBottom: 12,
  },
  joinToChatText: {
    fontSize: 16,
    color: "#666",
    textAlign: "center",
    marginBottom: 16,
  },
  joinButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  joinButtonText: {
    color: "white",
    textAlign: "center",
    fontSize: 16,
    fontWeight: "600",
  },
  emptyStateText: {
    color: "#999",
    fontSize: 16,
    marginTop: 16,
    textAlign: "center",
  },
  deletedInfoCard: {
    backgroundColor: "#fff8f8",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#ffcccc",
    alignItems: "center",
  },
  deletedInfoIcon: {
    marginBottom: 12,
  },
  deletedInfoTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#ff3b30",
    marginBottom: 8,
  },
  deletedInfoText: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 16,
  },
  restoreButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "white",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  restoreButtonText: {
    color: COLORS.primary,
    fontWeight: "600",
    fontSize: 14,
  },
  // Enhanced modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    width: "90%",
    maxHeight: "80%",
    backgroundColor: "#f8f8f8",
    borderRadius: 16,
    overflow: "hidden",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: "white",
  },
  modalHeaderContent: {
    flex: 1,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
  },
  modalSubtitle: {
    fontSize: 13,
    color: "#777",
    marginTop: 2,
  },
  modalDivider: {
    height: 1,
    backgroundColor: "#eee",
  },
  closeButton: {
    padding: 4,
  },
  modalNotice: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    backgroundColor: "#FFF9ED",
    borderRadius: 0,
    borderLeftWidth: 4,
    borderLeftColor: "#FF9500",
  },
  modalNoticeText: {
    flex: 1,
    fontSize: 13,
    color: "#734D00",
    lineHeight: 18,
  },
  membersList: {
    flexGrow: 1,
  },
  emptyStateContainer: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 40,
  },
  emptyText: {
    fontSize: 16,
    color: "#999",
    textAlign: "center",
    marginTop: 12,
  },
  bannedContainer: {
    alignItems: "center",
    padding: 16,
  },
  bannedIcon: {
    marginBottom: 12,
  },
  bannedTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#FF3B30",
    marginBottom: 8,
    textAlign: "center",
  },
  bannedDescription: {
    fontSize: 13,
    color: "#666",
    lineHeight: 20,
    textAlign: "center",
  },
});
