import { StyleSheet, Platform } from "react-native";
import { COLORS, FONT, SIZES } from "../../constants";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.lightWhite,
    marginBottom: 35,
  },
  scrollContent: {
    paddingBottom: 40,
  },
  headerContainer: {
    overflow: "hidden",
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: Platform.OS === "android" ? 40 : 30,
    paddingBottom: 70,
    alignItems: "center",
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
  },
  headerTitle: {
    color: COLORS.white,
    fontFamily: FONT.bold,
    fontSize: SIZES.xLarge + 2,
    marginTop: 10,
    letterSpacing: 0.5,
  },
  profileCard: {
    alignItems: "center",
    backgroundColor: COLORS.white,
    marginHorizontal: 16,
    marginTop: -50,
    borderRadius: 20,
    paddingVertical: 30,
    paddingHorizontal: 24,
    elevation: 8,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 15,
  },
  profileImageSection: {
    position: "relative",
    marginBottom: 18,
  },
  avatar: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 5,
    borderColor: COLORS.white,
  },
  avatarPlaceholder: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: COLORS.gray2,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 5,
    borderColor: COLORS.white,
  },
  editButton: {
    position: "absolute",
    bottom: 0,
    right: 0,
    backgroundColor: COLORS.primary,
    width: 38,
    height: 38,
    borderRadius: 19,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 3,
    borderColor: COLORS.white,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  fullName: {
    fontFamily: FONT.bold,
    fontSize: SIZES.large + 4,
    color: COLORS.primary,
    marginTop: 10,
    textAlign: "center",
  },
  email: {
    fontFamily: FONT.regular,
    fontSize: SIZES.medium,
    color: COLORS.gray,
    marginTop: 6,
    textAlign: "center",
  },
  memberSince: {
    fontFamily: FONT.medium,
    fontSize: SIZES.small + 1,
    color: COLORS.secondary,
    marginTop: 15,
    paddingHorizontal: 14,
    paddingVertical: 7,
    backgroundColor: "rgba(0, 0, 0, 0.05)",
    borderRadius: 12,
  },
  completionContainer: {
    width: "100%",
    marginTop: 25,
    paddingHorizontal: 8,
  },
  completionTextContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  completionText: {
    fontFamily: FONT.medium,
    fontSize: SIZES.medium,
    color: COLORS.primary,
  },
  completionPercentage: {
    fontFamily: FONT.bold,
    fontSize: SIZES.medium,
    color: COLORS.primary,
  },
  progressBarBackground: {
    height: 10,
    backgroundColor: "rgba(0, 0, 0, 0.08)",
    borderRadius: 5,
    overflow: "hidden",
  },
  progressBar: {
    height: 10,
    backgroundColor: COLORS.primary,
    borderRadius: 5,
  },
  completionTip: {
    marginTop: 8,
    fontFamily: FONT.regular,
    fontSize: SIZES.small + 1,
    color: COLORS.secondary,
    fontStyle: "italic",
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginTop: 30,
    paddingVertical: 22,
    paddingHorizontal: 15,
    backgroundColor: "rgba(0, 0, 0, 0.02)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(0, 0, 0, 0.03)",
  },
  statItem: {
    alignItems: "center",
    flex: 1,
  },
  statIconCircle: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  verticalDivider: {
    width: 1.5,
    height: "80%",
    backgroundColor: "rgba(0, 0, 0, 0.06)",
  },
  statNumber: {
    fontFamily: FONT.bold,
    fontSize: SIZES.large + 2,
    color: COLORS.primary,
  },
  statLabel: {
    fontFamily: FONT.regular,
    fontSize: SIZES.small + 1,
    color: COLORS.gray,
    marginTop: 6,
    textAlign: "center",
  },
  optionsContainer: {
    marginTop: 25,
    backgroundColor: COLORS.white,
    borderRadius: 20,
    marginHorizontal: 16,
    padding: 15,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  optionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 18,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0, 0, 0, 0.05)",
  },
  logoutRow: {
    borderBottomWidth: 0,
    marginTop: 5,
  },
  optionLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  iconBackground: {
    width: 48,
    height: 48,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
  },
  optionText: {
    fontSize: SIZES.medium + 2,
    fontFamily: FONT.medium,
    color: COLORS.primary,
  },
  logoutText: {
    color: "#FF5252",
    fontFamily: FONT.bold,
  },
  arrowContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(0, 0, 0, 0.06)",
    justifyContent: "center",
    alignItems: "center",
  },
  footer: {
    marginTop: 15,
    alignItems: "center",
    paddingBottom: 15,
  },
  versionText: {
    fontFamily: FONT.regular,
    fontSize: SIZES.small + 1,
    color: COLORS.gray,
  },
  // Modal styles
  modalBackdrop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#000",
    opacity: 0.5,
  },
  modalContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    paddingTop: 15,
    paddingBottom: 45,
    paddingHorizontal: 22,
    elevation: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -5 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
  },
  modalHandle: {
    width: 45,
    height: 5,
    backgroundColor: "#e0e0e0",
    borderRadius: 3,
    alignSelf: "center",
    marginBottom: 24,
  },
  modalContent: {
    alignItems: "center",
    paddingVertical: 20,
  },
  logoutIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#FF5252",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 24,
    elevation: 5,
    shadowColor: "#FF5252",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  logoutHeaderText: {
    fontFamily: FONT.bold,
    fontSize: SIZES.large + 6,
    color: COLORS.primary,
    marginBottom: 15,
  },
  logoutDescriptionText: {
    fontFamily: FONT.regular,
    fontSize: SIZES.medium + 1,
    color: COLORS.gray,
    textAlign: "center",
    marginBottom: 30,
    paddingHorizontal: 15,
    lineHeight: 22,
  },
  logoutButtonsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    paddingHorizontal: 10,
  },
  logoutButton: {
    flex: 1,
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 8,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
  },
  cancelButton: {
    backgroundColor: "#F3F3F3",
    borderWidth: 1,
    borderColor: "#E5E5E5",
  },
  confirmButton: {
    backgroundColor: "#FF5252",
  },
  cancelButtonText: {
    fontFamily: FONT.medium,
    fontSize: SIZES.medium + 1,
    color: COLORS.primary,
  },
  confirmButtonText: {
    fontFamily: FONT.medium,
    fontSize: SIZES.medium + 1,
    color: COLORS.white,
  },
  // Skeleton styles
  skeletonAvatar: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: COLORS.gray2,
    marginBottom: 18,
  },
  skeletonNameContainer: {
    alignItems: "center",
  },
  skeletonName: {
    width: 100,
    height: 20,
    backgroundColor: COLORS.gray2,
    borderRadius: 10,
    marginBottom: 6,
  },
  skeletonEmail: {
    width: 150,
    height: 16,
    backgroundColor: COLORS.gray2,
    borderRadius: 8,
    marginBottom: 15,
  },
  skeletonMember: {
    width: 120,
    height: 16,
    backgroundColor: COLORS.gray2,
    borderRadius: 8,
  },
  skeletonCompletionText: {
    width: 120,
    height: 16,
    backgroundColor: COLORS.gray2,
    borderRadius: 8,
  },
  skeletonCompletionPercentage: {
    width: 40,
    height: 16,
    backgroundColor: COLORS.gray2,
    borderRadius: 8,
  },
  skeletonProgressBar: {
    width: "100%",
    height: 10,
    backgroundColor: COLORS.gray2,
    borderRadius: 5,
  },
  skeletonStatIcon: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    backgroundColor: COLORS.gray2,
    marginBottom: 12,
  },
  skeletonStatNumber: {
    width: 30,
    height: 20,
    backgroundColor: COLORS.gray2,
    borderRadius: 10,
    marginBottom: 6,
  },
  skeletonStatLabel: {
    width: 60,
    height: 16,
    backgroundColor: COLORS.gray2,
    borderRadius: 8,
  },
});

export default styles;